### ISSUE TITLE
RuntimeError: expected scalar type float but found long int

### ISSUE THREAD

**Issue by takenori-y** [yoyololicon/torchcomp#3]
I am trying to wrap torchcomp as drc in diffsptk.

I got the following error (with torch 1.11.0, python 3.9):
```
RuntimeError: expected scalar type float but found long int
```

Could you replace `0` with `0.0` (or something) in the following lines?
https://github.com/yoyololicon/torchcomp/blob/6ed632a2c5fb9ae0f86593f0120e1bc22326ad77/torchcomp/core.py#L152
https://github.com/yoyololicon/torchcomp/blob/6ed632a2c5fb9ae0f86593f0120e1bc22326ad77/torchcomp/core.py#L154

**Comment by yoyolicoris** [comment]
Hi @takenori-y, thanks for spotting the issue!
I didn't test this on pytorch<2.0 before. Good catch. Will fix it soon.

**Comment by yoyolicoris** [comment]
fixed in cbe46c54ae9b0aa212911cd1dc5ec6b130acfd2c

**Comment by takenori-y** [comment]
Thanks for the quick fix!
It would be appreciated if you could update the pypi package at your convenience.

**Comment by yoyolicoris** [comment]
@takenori-y I have updated the pypi https://pypi.org/project/torchcomp/0.1.1/

**Comment by takenori-y** [comment]
@yoyololicon
Thank you for taking time! I have successfully added the module in diffsptk (https://github.com/sp-nitech/diffsptk/pull/76).
